# Generated by Django 5.1 on 2025-04-06 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название способа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ вывода',
                'verbose_name_plural': 'Способы вывода',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Выполнена')], default='pending', max_length=50, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payouts.payoutmethod', verbose_name='Способ вывода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на вывод средств',
                'verbose_name_plural': 'Запросы на вывод средств',
                'ordering': ['-created_at'],
            },
        ),
    ]
