# Generated by Django 5.1 on 2025-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='balance_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
