# Generated by Django 5.1 on 2025-05-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payoutrequest_balance_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutmethod',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='payout_logos/', verbose_name='Логотип'),
        ),
    ]
