# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOLoginToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("partner", models.CharField(default="medcrm", max_length=100)),
                ("next_path", models.CharField(default="/", max_length=512)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_login_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["partner", "token_hash"], name="integration_partner_1abfcf_idx"),
                    models.Index(fields=["user", "-created_at"], name="integration_user_id_c0e917_idx"),
                    models.Index(fields=["expires_at"], name="integration_expires_e8a3fc_idx"),
                ],
            },
        ),
    ]
