from django.urls import path

from .views import (
    MedCRMInviteClientView,
    MedCRMTariffsView,
    SecondSystemWebviewUrlView,
    TelegramAdminWebhookView,
    TelegramAuthStartView,
    TelegramAuthStatusView,
    TelegramAuthWebhookView,
    VerifySecondSystemSSOTokenView,
    MamadocAppointmentsView,
    MamadocConclusionView,
    MamadocBookingView,
    MamadocBookingCancelView,
    MamadocProfessionalsView,
    MamadocServicesView,
    MamadocOrganizationView,
    MamadocBranchesView,
)

app_name = "integrations"

urlpatterns = [
    path(
        "telegram/auth/start/",
        TelegramAuthStartView.as_view(),
        name="telegram-auth-start",
    ),
    path(
        "telegram/auth/status/",
        TelegramAuthStatusView.as_view(),
        name="telegram-auth-status",
    ),
    path(
        "telegram/auth/webhook/",
        TelegramAuthWebhookView.as_view(),
        name="telegram-auth-webhook",
    ),
    path(
        "telegram/auth/webhook/<str:webhook_secret>/",
        TelegramAuthWebhookView.as_view(),
        name="telegram-auth-webhook-secret",
    ),
    path(
        "telegram/admin/webhook/<str:webhook_secret>/",
        TelegramAdminWebhookView.as_view(),
        name="telegram-admin-webhook",
    ),
    path(
        "medcrm/tariffs/",
        MedCRMTariffsView.as_view(),
        name="medcrm-tariffs",
    ),
    path(
        "medcrm/invite-client/",
        MedCRMInviteClientView.as_view(),
        name="medcrm-invite-client",
    ),
    path(
        "medcrm/webview-url/",
        SecondSystemWebviewUrlView.as_view(),
        name="medcrm-sso-webview-url",
    ),
    path(
        "medcrm/verify-sso-token/",
        VerifySecondSystemSSOTokenView.as_view(),
        name="medcrm-sso-verify-token",
    ),
    path(
        "newcrm/professionals/",
        MamadocProfessionalsView.as_view(),
        name="newcrm-professionals",
    ),
    path(
        "newcrm/services/",
        MamadocServicesView.as_view(),
        name="newcrm-services",
    ),
    path(
        "newcrm/organization/",
        MamadocOrganizationView.as_view(),
        name="newcrm-organization",
    ),
    path(
        "newcrm/branches/",
        MamadocBranchesView.as_view(),
        name="newcrm-branches",
    ),
    path(
        "newcrm/appointments/",
        MamadocAppointmentsView.as_view(),
        name="newcrm-appointments",
    ),
    path(
        "newcrm/conclusions/<int:conclusion_id>/",
        MamadocConclusionView.as_view(),
        name="newcrm-conclusion-detail",
    ),
    path(
        "newcrm/booking/appointments/",
        MamadocBookingView.as_view(),
        name="newcrm-booking-appointments",
    ),
    path(
        "newcrm/booking/appointments/<int:appointment_id>/cancel/",
        MamadocBookingCancelView.as_view(),
        name="newcrm-booking-appointment-cancel",
    ),
]
