# Generated by Django 5.1 on 2025-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_servicestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
    ]
