# Generated by Django 5.1 on 2025-04-05 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пакета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('duration_hours', models.PositiveIntegerField(default=24, verbose_name='Срок действия (в часах)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('tariff_type', models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный')], default='paid', max_length=255, verbose_name='Тип пакета')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='AccessOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный')], default='paid', max_length=255, verbose_name='Тип пакета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Успешно'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата инициации')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало пакета')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец пакета')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat_access.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заказ доступа',
                'verbose_name_plural': 'Заказы доступа',
                'ordering': ['-created_at'],
            },
        ),
    ]
