# Generated by Django 5.1 on 2025-04-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorder',
            name='duration_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Срок действия (в часах)'),
        ),
    ]
