# Generated by Django 5.1 on 2025-04-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0002_accessorder_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorder',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок действия (в часах)'),
        ),
        migrations.AlterField(
            model_name='accessorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='accessorder',
            name='tariff_type',
            field=models.CharField(blank=True, choices=[('free', 'Бесплатный'), ('paid', 'Платный')], max_length=255, null=True, verbose_name='Тип пакета'),
        ),
    ]
