# Generated by Django 5.1 on 2025-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0005_chat_accessorder_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
