# Generated by Django 5.1 on 2026-01-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0006_tariff_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Виден клиентам'),
        ),
    ]
