# Generated by Django 5.1 on 2026-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0007_tariff_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='specialist_note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка специалиста о клиенте'),
        ),
    ]
