# Generated by Django 5.1 on 2026-02-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0008_chat_specialist_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='client_can_send_voice',
            field=models.BooleanField(default=True, verbose_name='Клиент может отправлять голосовые'),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
