# Generated by Django 5.1 on 2026-03-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_access", "0009_chat_client_can_send_voice_chat_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="chat_access.chat", verbose_name="Чат")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorite_chats", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Избранный чат",
                "verbose_name_plural": "Избранные чаты",
            },
        ),
        migrations.AddConstraint(
            model_name="favoritechat",
            constraint=models.UniqueConstraint(fields=("user", "chat"), name="unique_favorite_chat_per_user"),
        ),
        migrations.AddIndex(
            model_name="favoritechat",
            index=models.Index(fields=["user", "-created_at"], name="chat_access__user_id_2047df_idx"),
        ),
        migrations.AddIndex(
            model_name="favoritechat",
            index=models.Index(fields=["chat"], name="chat_access__chat_id_183ce8_idx"),
        ),
    ]
