# Generated by Django 5.1 on 2026-03-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_access", "0010_favoritechat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocked_entries", to="chat_access.chat", verbose_name="Чат")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocked_chats", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Чат в черном списке",
                "verbose_name_plural": "Чаты в черном списке",
            },
        ),
        migrations.AddConstraint(
            model_name="blockedchat",
            constraint=models.UniqueConstraint(fields=("user", "chat"), name="unique_blocked_chat_per_user"),
        ),
        migrations.AddIndex(
            model_name="blockedchat",
            index=models.Index(fields=["user", "-created_at"], name="chat_access__user_id_4a793c_idx"),
        ),
        migrations.AddIndex(
            model_name="blockedchat",
            index=models.Index(fields=["chat"], name="chat_access__chat_id_b5bf81_idx"),
        ),
    ]
