# Generated by Django 5.1 on 2026-04-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_access', '0012_chat_soft_delete'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blockedchat',
            new_name='chat_access_user_id_14ca54_idx',
            old_name='chat_access__user_id_4a793c_idx',
        ),
        migrations.RenameIndex(
            model_name='blockedchat',
            new_name='chat_access_chat_id_b76dfb_idx',
            old_name='chat_access__chat_id_b5bf81_idx',
        ),
        migrations.RenameIndex(
            model_name='favoritechat',
            new_name='chat_access_user_id_6a8fdf_idx',
            old_name='chat_access__user_id_2047df_idx',
        ),
        migrations.RenameIndex(
            model_name='favoritechat',
            new_name='chat_access_chat_id_1a21d8_idx',
            old_name='chat_access__chat_id_183ce8_idx',
        ),
    ]
