# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_access", "0013_rename_chat_access__user_id_4a793c_idx_chat_access_user_id_14ca54_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="Популярный"),
        ),
    ]
