# Generated by Django 5.1 on 2025-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Клиент'), ('specialist', 'Специалист')], max_length=20, verbose_name='Роль'),
        ),
    ]
