# Generated by Django 5.1 on 2025-03-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_otp_user_mobile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_otp',
        ),
    ]
