# Generated by Django 5.1 on 2025-04-01 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_mobile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='professioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='account.professioncategory'),
        ),
    ]
