# Generated by Django 5.1 on 2025-04-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='account.professioncategory', verbose_name='Профессия'),
        ),
    ]
