# Generated by Django 5.1 on 2025-04-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workschedule',
            name='unique_user_day_of_week',
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('user', 'day_of_week')},
        ),
    ]
