# Generated by Django 5.1 on 2025-05-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Клиент'), ('specialist', 'Специалист')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
