# Generated by Django 5.1 on 2025-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.CharField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
    ]
