# Generated by Django 5.1 on 2025-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_user_education_alter_user_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_greeting',
            field=models.TextField(blank=True, null=True, verbose_name='Приветственный текст для приглашения'),
        ),
    ]
