# Generated by Django 5.1 on 2025-07-14 10:15
import uuid

import django.contrib.auth.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_otp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                null=True,
                blank=True,
                verbose_name='username',
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                error_messages={'unique': 'A user with that username already exists.'},
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name='phone number'),
        ),
    ]
