# Generated by Django 5.1 on 2025-07-21 12:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG', verbose_name='Старый номер телефона'),
        ),
    ]
