# Generated by Django 5.1 on 2025-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_user_old_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_call',
            field=models.BooleanField(default=True, verbose_name='Можно ли звонить этому пользователю'),
        ),
    ]
