# Generated by Django 5.1 on 2025-08-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_user_can_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_call',
        ),
        migrations.AddField(
            model_name='user',
            name='can_audio_call',
            field=models.BooleanField(default=True, verbose_name='Можно ли звонить пользователю (АУДИО)'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_video_call',
            field=models.BooleanField(default=True, verbose_name='Можно ли звонить пользователю (ВИДЕО)'),
        ),
    ]
