# Generated by Django 5.1 on 2026-02-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='is_day_off',
            field=models.BooleanField(default=False, verbose_name='Выходной'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='is_round_the_clock',
            field=models.BooleanField(default=False, verbose_name='Круглосуточно'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='to_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
