# Generated by Django 5.1 on 2026-03-01 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_workschedule_is_day_off_and_more'),
        ('chat_access', '0009_chat_client_can_send_voice_chat_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push')], max_length=10, verbose_name='Канал доставки')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка')], max_length=20, verbose_name='Статус доставки')),
                ('is_new_client', models.BooleanField(default=False, verbose_name='Новый клиент')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID сообщения у провайдера')),
                ('provider_status', models.CharField(blank=True, default='', max_length=255, verbose_name='Статус провайдера')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_deliveries', to='chat_access.chat', verbose_name='Чат')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_deliveries_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_deliveries_as_specialist', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Доставка приглашения',
                'verbose_name_plural': 'Доставки приглашений',
                'ordering': ('-created_at',),
            },
        ),
    ]
