# Generated by Django 5.1 on 2026-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_invitedelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия (свой вариант)'),
        ),
    ]
