# Generated by Django 5.1 on 2026-03-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='account.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.organization', verbose_name='Организация'),
        ),
    ]
