# Generated by Django 5.1 on 2026-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_application_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация (свой вариант)'),
        ),
    ]
