# Generated by Django 5.1 on 2026-03-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_application_custom_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
                ("notification_type", models.CharField(choices=[("system", "Системное"), ("payment_success", "Успешная оплата"), ("chat_invite", "Приглашение в чат"), ("application_accepted", "Заявка одобрена")], db_index=True, default="system", max_length=50, verbose_name="Тип уведомления")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Доп. данные")),
                ("is_read", models.BooleanField(db_index=True, default=False, verbose_name="Прочитано")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата прочтения")),
                ("pushed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата push-отправки")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL, verbose_name="Получатель")),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "-created_at"], name="account_noti_recipie_867449_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "notification_type", "-created_at"], name="account_noti_recipie_52deee_idx"),
        ),
    ]
