# Generated by Django 5.1 on 2026-03-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='account_not_recipie_aafcaa_idx',
            old_name='account_noti_recipie_867449_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='account_not_recipie_3711b9_idx',
            old_name='account_noti_recipie_52deee_idx',
        ),
    ]
