# Generated by Codex on 2026-05-04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_rename_account_noti_recipie_867449_idx_account_not_recipie_aafcaa_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
