# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0043_organization_rating_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/logos/",
                verbose_name="Логотип",
            ),
        ),
    ]
