# Generated by Django 5.1 on 2026-05-14 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_organization_logo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='social_networks/logos/', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Адрес организации',
                'verbose_name_plural': 'Адреса организаций',
                'ordering': ('-is_primary', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('image', models.ImageField(upload_to='organizations/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='account.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Фото галереи организации',
                'verbose_name_plural': 'Фото галереи организаций',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Услуга организации',
                'verbose_name_plural': 'Услуги организаций',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('from_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('to_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('is_round_the_clock', models.BooleanField(default=False, verbose_name='Круглосуточно')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='account.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'График работы организации',
                'verbose_name_plural': 'Графики работы организаций',
                'ordering': ('day_of_week',),
                'unique_together': {('organization', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка / username')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='account.organization', verbose_name='Организация')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='account.socialnetwork', verbose_name='Социальная сеть')),
            ],
            options={
                'verbose_name': 'Соцсеть организации',
                'verbose_name_plural': 'Соцсети организаций',
                'unique_together': {('organization', 'social_network')},
            },
        ),
    ]
