# Generated by Django 5.1 on 2026-08-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_otp_channel_otp_sms_resent_at'),
        ('push_notifications', '0011_alter_apnsdevice_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя успешная отправка')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя неудачная отправка')),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Код последней ошибки')),
                ('last_error_message', models.TextField(blank=True, default='', verbose_name='Текст последней ошибки')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда токен признан нерабочим')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='push_notifications.gcmdevice', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Состояние push-устройства',
                'verbose_name_plural': 'Состояния push-устройств',
            },
        ),
    ]
