# Generated by Django 5.1 on 2026-09-16 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_schedule_lunch_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_profession_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Описание профессии (свой вариант)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Системное'), ('payment_success', 'Успешная оплата'), ('chat_invite', 'Приглашение в чат'), ('application_accepted', 'Заявка одобрена'), ('application_rejected', 'Заявка отклонена'), ('profession_request_approved', 'Профессия добавлена'), ('profession_request_rejected', 'Заявка на профессию отклонена'), ('erkinai', 'Из ErkinAI')], db_index=True, default='system', max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.CreateModel(
            name='ProfessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название профессии')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('source', models.CharField(choices=[('application', 'Анкета специалиста'), ('profile', 'Профиль')], default='profile', max_length=20, verbose_name='Откуда подана')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profession_request', to='account.application', verbose_name='Анкета')),
                ('profession_category', models.ForeignKey(blank=True, help_text='Оставьте пустым — при одобрении категория будет создана по названию заявки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession_requests', to='account.professioncategory', verbose_name='Категория после одобрения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на профессию',
                'verbose_name_plural': 'Заявки на профессии',
                'ordering': ('-created_at',),
            },
        ),
    ]
