# Generated by Django 5.1 on 2026-09-28 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_profession_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_working_dates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Нерабочая дата',
                'verbose_name_plural': 'Нерабочие даты',
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_non_working_date')],
            },
        ),
    ]
