# Generated by Django 5.1 on 2025-03-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('organizations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('pay_method', models.CharField(choices=[('cash', 'Наличные'), ('mbank', 'Mbank')], max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], max_length=50, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.organization', verbose_name='Организация')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient', verbose_name='Пациент')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Услуга в транзакции',
                'verbose_name_plural': 'Услуги в транзакциях',
            },
        ),
    ]
